### ISSUE TITLE
Provide feedback to the PID group

### ISSUE THREAD

**Issue by alexpearce** [alexpearce/CharmProduction#12]
The PID group need an idea of what kinematics and statistics they should provide to minimise restrictions on the early measurements.

We need to provide a sample with kinematics — momentum, transverse momentum, and psuedorapidity — representative of our decays modes.

There is also a potential problem in the the pion/kaon PID calibration, which is made using D*-tagged D0 to K-pi+ decays. We need to check the overlap of the PID selection with our own. A large overlap will mean having to account for correlations in the PID efficiency.

**Comment by alexpearce** [comment]
@dominikmuller This is done now isn't it?

**Comment by dominikmuller** [comment]
I send the stuff to Barbara but haven't heard back. I will send another mail. But basically it's done.
