### ISSUE TITLE
BDT code on clang++

### ISSUE THREAD

**Issue by dominikmuller** [alexpearce/CharmProduction#20]
The BDT training code produces a segmentation fault when compiled using clang++. g++ compiles fine and runs on LXPLUS. I will take care of this issue over Christmas as I have to rewrite (wanted to do that anyway) my Config class.

**Comment by chrisburr** [comment]
Am I correct in thinking this is now fixed?

**Comment by dominikmuller** [comment]
Well using --silent it will work for now. If I have too much time and nothing else to do at some point ( aka never) I want to really understand and fix the problem.

**Comment by alexpearce** [comment]
It works for me so I'm happy for this to be closed. I agree it's an interesting problem though…
