### ISSUE TITLE
Have 2015 ntuple code use DaVinci v36r3

### ISSUE THREAD

**Issue by alexpearce** [alexpearce/CharmProduction#24]
See Eduardo's email on the lhcb-davinci listing “[Releases of DaVinci v36r3(p1) based on ROOT5(6)](https://groups.cern.ch/group/lhcb-davinci/Lists/Archive/Flat.aspx?RootFolder=%2Fgroup%2Flhcb-davinci%2FLists%2FArchive%2FReleases%20of%20DaVinci%20v36r3%28p1%29%20based%20on%20ROOT5%286%29&FolderCTID=0x01200200B795ECDBD8943F4E90E5F02A017196C9)”. DaVinci v36r3 is the first release fully supporting the early measurements.

I think the update is [mostly Tesla related](http://lhcb-release-area.web.cern.ch/LHCb-release-area/DOC/davinci/releases/v36r3/release.notes.php) and the addition of the 2015 `DataType`. It probably won't affect the actual ntuple creation much, but we should stay current where relevant.

**Comment by chrisburr** [comment]
Fixed as of https://github.com/alexpearce/CharmProduction/commit/1a02c00fa98c741fa9dd0a1d97947b1090617e80
