### ISSUE TITLE
Generate sWeights from the fit

### ISSUE THREAD

**Issue by alexpearce** [alexpearce/CharmProduction#28]
[sWeights](http://arxiv.org/abs/physics/0402083) allow the extraction of species-specific distributions from a mixture. Information from an extended maximum likelihood fit can be used to generate per-species weights, which can be used to create the species-specific distributions. It's effectively a fancy and much more statistically powerful sideband subtraction, allowing for arbitrary background and signal shapes.

Having sWeights is often useful, for example when comparing fully selected signal in data with signal Monte Carlo. RooFit allows for [simple calculation](https://root.cern.ch/root/html/RooStats__SPlot.html) of sWeights from a fit. We should add these to our selected ntuples.

**Comment by alexpearce** [comment]
(Reminder for myself.)

As raised in the [16/01/2015 meeting](https://indico.cern.ch/event/365707/), we could model the background distribution using the [sFit](http://arxiv.org/abs/0905.0724) technique, using background sWeights from the mass fit to create the background PDF in the IP χ<sup>2</sup> fits

**Comment by alexpearce** [comment]
This might be annoying, because when the [`RooDataSet`](https://root.cern.ch/root/html600/RooDataSet) is created from the ntuple any events with branch values that fall outside the defined ranges of the variables of the dataset are discarded (e.g. if the `mass` variable in the dataset has the range 1800–1900, any ntuples with `mother_M` outside this range aren't imported).

When you loop over the input tree to create the sWeight friend tree, the dataset is then (usually) smaller, so you need to match dataset entries to the correct `TTree` entries. I guess you could check that the variables in the two source are ‘very close’, `dataset_value - ttree_value < epsilon`, but I'm not certain that would always work…

**Comment by alexpearce** [comment]
With #84, using sWeights in the fit is actually pretty simple. You just call `fitting.mass.fit` with `sweights=True`, and the `RooDataSet` used for the fitting will automatically have a `yield_sig_sw` and a `yield_bkg_sw` weight for every event.

It's still a problem getting these sWeights out and using them with other variables though, for the reason outlined above: when you create the `RooDataSet`, any events falling outside the ranges of any variables inside the set are thrown anyway, so you'll have trouble matching the sWeights back to the correct events in the original tree.

For now this isn't a problem, and so this issue will be closed once #84 has been merged. We should open a new issue if not having sWeights outside the fit becomes a problem.

**Comment by dominikmuller** [comment]
Might be worth opening a new issue for this friend tree matching, at least if we decide to use sWeighted data as the reference sample for PID.

**Comment by alexpearce** [comment]
OK, if the arises please open one then. I'll close this now as sWeights in the fit are fully integrated since [`e5d603`](https://github.com/alexpearce/CharmProduction/commit/e5d6038757b3cda9fe38e5bb9e365de2a6de8ff6).
