### ISSUE TITLE
Data source to test stripping cuts on

### ISSUE THREAD

**Issue by chrisburr** [alexpearce/CharmProduction#50]
We need to decide which data to test the stripping cuts on.

### Signal

I guess the best thing to use is Cheated MC. If so should we use:
 - the MC the BDT is trained on?
 - random sample from the MC set which is used for calculating efficiencies?
 - a separate sample of the MC?

My thinking is a separate MC sample seeming as we can always generate more MC if needed.

### Background
I think this is a little tricker. Any of the above options using minbias MC will ignore any combinatorial backgrounds which I assume we need? So is the only solution to have another tuple in the `DVntuple.root` file with modified stripping line to have no cuts applied at all?

To get a feel for the number of events in the full minbias dataset in both polarities we have:

Mode | Cheated BKGCAT < 11 | Cheated BKGCAT > 10 | Stripped BKGCAT < 11 | Stripped BKGCAT > 10
------------ | ------------- | ------------- | ------------- | -------------
D0Tohh | 19,412 | 138,112 | 5,251 | 1,123,538

**Comment by alexpearce** [comment]
### Signal

Would have thought to use the cheated MC for training the preselection, then use preselected and cheated MC for training and testing the BDT.

### Background

An appropriate background sample for some modes might be minbias that has been combined in the same way as signal, e.g. for D0ToKpipipi use four track combinations.

**Comment by chrisburr** [comment]
So the best option is probably to create another ntuple during `setup_data` called `train_stripping_sig.root`.

For the background minbias am I right in thinking we need to run DaVinci again to create this new tree?

**Comment by alexpearce** [comment]
Hmm unfortunately I think so. It will basically be the cheated ntuples but without `mcMatch`.

**Comment by chrisburr** [comment]
As we have decided this isn't needed for now I'm going to close this.
