### ISSUE TITLE
Invisible text on fit plots

### ISSUE THREAD

**Issue by alexpearce** [alexpearce/CharmProduction#79]
The changes introduced by #55 make the legend text on fitting plots invisible. Example:

![post_changes](https://cloud.githubusercontent.com/assets/540853/6150366/458b16da-b20f-11e4-8b6f-8e441137957e.png)

Reference before the changes:

![pre_changes](https://cloud.githubusercontent.com/assets/540853/6150374/4b610218-b20f-11e4-8892-fc4f274df141.png)

**Comment by alexpearce** [comment]
Here's the result after removing [this line](https://github.com/alexpearce/CharmProduction/blob/master/analysis/charmproduction/plotting/utilities.py#L114) and [this line](https://github.com/alexpearce/CharmProduction/blob/master/analysis/charmproduction/plotting/plot_fit.py#L75):

![no-settextsize](https://cloud.githubusercontent.com/assets/540853/6151751/22ead918-b218-11e4-8cd4-8dfc464ef9b1.png)

The above lines adjust the text size based on point (pt) size, but the new styles use relative sizing, which has "sane" text values closer to 0.1. The massive text wasn't being rendered, though it was present.

Better, still some tweaking to do before these are showable externally I think.

**Comment by alexpearce** [comment]
@dominikmuller Would you prefer I work on tweaking the looks of these, or do you want to do it?

**Comment by dominikmuller** [comment]
I already started. Will do that first thing tomorrow. Already fixed the label sizes. Got to fix the parameter table and make the markers work properly.

**Comment by dominikmuller** [comment]
And the tex plot stuff was my idea so I'll make sure that it will work.

**Comment by alexpearce** [comment]
Great, thanks!

**Comment by alexpearce** [comment]
I'm closing this as I know it's been fixed by #80.
