### ISSUE TITLE
DaVinci Bug - isTheMotherCorrectlyIdentified

### ISSUE THREAD

**Issue by chrisburr** [alexpearce/CharmProduction#83]
When running over some MC datasets [`TupleToolMCTruth`](https://github.com/alexpearce/CharmProduction/blob/isTheMother-bug-example/options/helpers/tuple_templates.py#L49) and [`TupleToolMCBackgroundInfo`](https://github.com/alexpearce/CharmProduction/blob/isTheMother-bug-example/options/helpers/tuple_templates.py#L100) result in DaVinci crashing.

I've pushed [a branch](https://github.com/alexpearce/CharmProduction/tree/isTheMother-bug-example) which demonstrates the crash in interactive mode when you run `ganga ganga_simulation_S20.py -t MagDown 2015 30000000`. There is a `CRASH` flag in `helpers/tuple_templates.py` which can be switched to enable/disable the problematic tools.

**Comment by alexpearce** [comment]
[Link to mailing list discussion](https://groups.cern.ch/group/lhcb-davinci/Lists/Archive/Flat.aspx?RootFolder=%2Fgroup%2Flhcb-davinci%2FLists%2FArchive%2FSegmentation%20fault%20when%20requiring%20TupleToolMCTruth&FolderCTID=0x01200200B795ECDBD8943F4E90E5F02A017196C9), for reference.

**Comment by chrisburr** [comment]
And to the [JIRA task](https://its.cern.ch/jira/browse/LHCBPS-1400).

**Comment by alexpearce** [comment]
Vava has [committed a fix](https://svnweb.cern.ch/trac/lhcb/changeset/184013) for the background category tool, does this solve things, can we use all the tools OK?
