### ISSUE TITLE
‘Studies’ folder

### ISSUE THREAD

**Issue by alexpearce** [alexpearce/CharmProduction#96]
What do you guys think about having a ‘studies’ folder at `analysis/studies`? We could put little scripts that aren't really part of the main analysis but that we've written to ‘test’ something.

I've got two scripts that I've not committed yet that would fit: a example of using sWeights from the fit that plots the various sWeighted distributions in IP \chi^{2}, and something that creates tables showing the difference between running  the new and old fitter on 2010 data.

**Comment by dominikmuller** [comment]
Sounds good, I have the scripts for the binning scheme generation and cut comparison to add.

**Comment by chrisburr** [comment]
This can be closed?
